FROM ubuntu-rstudio-2-rstudio

RUN apt-get update -y && \
    apt-get install -y default-jre default-jdk
	
RUN java -version && javac -version

# RUN ls /usr/lib/jvm

# ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b08-1.amzn2.0.1.x86_64

