name: Ubuntu RStudio CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.AWS_RSTUDIO_CONTAINER_PAT }}

    - name: Build
      run: |
        docker build --progress plain -t ubuntu-rstudio-1-system ubuntu-rstudio-1-system
        docker build --progress plain -t ubuntu-rstudio-2-rstudio ubuntu-rstudio-2-rstudio
        docker build --progress plain -t ubuntu-rstudio-3-java ubuntu-rstudio-3-java
        docker build --progress plain -t ubuntu-rstudio-4-r ubuntu-rstudio-4-r
        docker build --progress plain -t ubuntu-rstudio-5-rpackages ubuntu-rstudio-5-rpackages
        docker build --progress plain -t ubuntu-rstudio ubuntu-rstudio-6-other
        
    - name: Push to Github Container Repository
      run: |
        docker tag ubuntu-rstudio ghcr.io/bertcarnell/ubuntu-rstudio:latest
        docker push ghcr.io/bertcarnell/ubuntu-rstudio:latest
